os: linux
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

jobs:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction --no-suggest --ignore-platform-reqs

before_script:
  - curl --silent -L https://phar.phpunit.de/phpunit-8.phar --create-dirs --output vendor/bin/phpunit
  - chmod +x vendor/bin/phpunit

script:
  - vendor/bin/phpunit
